apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: flying-marsupial-python 
  janus-idp.io/tekton: flying-marsupial-python
  backstage.io/kubernetes-id: flying-marsupial-python
  backstage.io/kubernetes-namespace: oc-ci-e2e 
  app.kubernetes.io/part-of: flying-marsupial-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  